spring:
  application:
    name: eureka-consumer

management:
  security:
    enabled: false

server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

info:
  title: im a consumer

eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule